# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160830_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='wlasne', max_length=64),
        ),
    ]
