# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160831_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
