# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160831_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
